# Generated by Django 2.2.3 on 2019-07-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery',
            field=models.IntegerField(choices=[(1, '택배거래'), (2, '직거래'), (3, '택배/직거래')], verbose_name='거래 방법'),
        ),
    ]
